### ISSUE TITLE
Maybe there is some error on the server at p3_extra in turn_in, no compiling error

### ISSUE THREAD

**Issue by WERDXZ** [shelleywong/CSCI211-Course-Materials#2]
the file runs locally on my laptop with the same output, I've tested the code and found out that the regex on the turn_in is not working(maybe). I also tested it on my Linux machine and it also worked

I've attached the compiled file.

JQ Yang, student#011696192

[vlist.zip](https://github.com/shelleywong/CSCI211-Course-Materials/files/9523723/vlist.zip)

**Comment by shelleywong** [comment]
There is a way to pass the regex tests that should work on any server (including Turnin); however, Turnin uses an older version of Linux, so there are occasionally things that don't work on Turnin that do work on your Linux machine. Turnin has some known issues that are beyond my control, but there is currently work in progress to find a new option for students to submit assignments. I saw that your code passed on my version of Ubuntu 22.04, so I will give you credit for passing the regex tests.

**Comment by shelleywong** [comment]
Hi JQ,

There is a way to pass the regex tests that works on Turnin; however,
Turnin uses an older version of Linux, so occasionally there are things
that work on a newer version of Linux that do not work on Turnin. (There
are some known issues with Turnin, but these are beyond my control. There
is currently work in progress to address the issues with Turnin). I saw
that your code worked on Ubuntu 22.04, and there was nothing that stood out
to me that needed to be changed, so I will give you credit for passing the
regex tests.

Shelley
