### ISSUE TITLE
There definitely something wrong with the p5_extra output

### ISSUE THREAD

**Issue by WERDXZ** [shelleywong/CSCI211-Course-Materials#3]
on the t90.out
line 323 to line 325 as below:

  161: s990 stole $394 and 4 items from checker 9
  162: s745 entered store
  162: s48 done shopping, waiting for checker 9

the cmd file is:
  10 2 tests/t90.in results/t90.myout

which means there is a break of 2(t) after being robbed
but the output in t90.out line 323 to line 325 doesn't follow the rule

I'll attach all the files 
[p5_extra.zip](https://github.com/shelleywong/CSCI211-Course-Materials/files/9561654/p5_extra.zip)

**Comment by shelleywong** [comment]
The original creator of this assignment had an oversight here, but I've updated the instructions to match the expected output. When a shopper is done shopping, put the customer on the checker with the fewest number of customers (regardless of whether the checker is on break). This will work out in the shopper's favor more often, as the time it takes to checkout one customer is greater than the checker's break time in most cases.

**Comment by WERDXZ** [comment]
wow
it works
